import React from 'react';

interface TermsOfServiceViewProps {
  onBack: () => void;
}

const TermsOfServiceView: React.FC<TermsOfServiceViewProps> = ({ onBack }) => {
  return (
    <div className="h-full bg-gray-900 overflow-y-auto pb-safe">
      <div className="sticky top-0 bg-gray-900 border-b border-gray-800 p-4 flex items-center z-10">
        <button 
          onClick={onBack}
          className="flex items-center text-gray-400 hover:text-white transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back
        </button>
        <h1 className="ml-4 text-lg font-bold text-white">Terms of Service</h1>
      </div>

      <div className="p-6 max-w-2xl mx-auto text-gray-300 space-y-6">
        <div className="space-y-2">
          <p className="text-sm text-gray-500">Last Updated: October 26, 2023</p>
          <p>
            By using the My Church Bible Study app, you agree to the following terms and conditions. Please read them carefully.
          </p>
        </div>

        <section className="space-y-2">
          <h2 className="text-xl font-bold text-white">1. Use of the App</h2>
          <p>
            This application is designed to help users engage with their church sermons through AI-generated study plans. You agree to use this app only for lawful purposes and in accordance with these Terms.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-bold text-white">2. AI-Generated Content Disclaimer</h2>
          <p>
            The Bible studies, devotionals, and summaries provided by this app are generated by Artificial Intelligence (Google Gemini). 
          </p>
          <div className="bg-yellow-900/20 border-l-4 border-yellow-600 p-4">
            <p className="text-yellow-200 text-sm">
              <strong>Important:</strong> AI can make mistakes. The theological content, scripture references, and summaries may occasionally contain inaccuracies. We strongly recommend verifying all content with your Bible and church leadership.
            </p>
          </div>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-bold text-white">3. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You are responsible for maintaining the confidentiality of your account information.</li>
            <li>You agree not to upload audio or images that contain illegal, offensive, or copyrighted material you do not have permission to use.</li>
            <li>You acknowledge that recording public speakers may require consent in certain jurisdictions. Please ensure you have permission to record sermons.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-bold text-white">4. Availability and Data</h2>
          <p>
            We strive to ensure the app is available and functional, but we cannot guarantee uninterrupted service. As data is stored locally on your device, we are not responsible for data loss resulting from device failure, clearing browser cache, or other local issues.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-bold text-white">5. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the application following any changes indicates your acceptance of the new terms.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfServiceView;